"""empty message

Revision ID: 130e82624186
Revises: 22f4dc3ea73c
Create Date: 2023-03-20 12:02:17.387705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130e82624186'
down_revision = '22f4dc3ea73c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
